terabot:
  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_1_joint
    pid: {p: 500.0, i: 20.0, d: 5.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_2_joint
    pid: {p: 700.0, i: 30.0, d: 5.0}
  
  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_5_joint
    pid: {p: 800.0, i: 30, d: 0.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_8_joint
    pid: {p: 200.0, i: 20, d: 5.0}

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_9_joint
    pid: {p: 400.0, i: 15, d: 0.0}
    
  jg1_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_91_joint
    pid: {p: 100.0, i: 0.1, d: 0.1}
    
  jg2_position_controller:
    type: effort_controllers/JointPositionController
    joint: terabot_92_joint
    pid: {p: 100.0, i: 0.1, d: 0.1}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
